    # Publish joint states
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    panda_arm_controller:
        type: velocity_controllers/JointTrajectoryController
        joints:
            - panda_joint1
            - panda_joint2
            - panda_joint3
            - panda_joint4
            - panda_joint5
            - panda_joint6
            - panda_joint7

        gains:
            panda_joint1: { p: 10000.0, i: 1.0, d: 1000.0, i_clamp: 10 }
            panda_joint2: { p: 100.0, i: 0.1, d: 20.0, i_clamp: 1.0 }
            panda_joint3: { p: 500.0, i: 0.01, d: 10.0, i_clamp: 0.1 }
            panda_joint4: { p: 400.0, i: 0.0, d: 10.0, i_clamp: 0.0 }
            panda_joint5: { p: 6.5, i: 0.0, d: 0.01, i_clamp: 0.0 }
            panda_joint6: { p: 8.0, i: 0.0, d: 0.01, i_clamp: 0.0 }
            panda_joint7: { p: 12.0, i: 0.0, d: 0.1, i_clamp: 0.0 }

        constraints:
            goal_time: 2.0

        state_publish_rate: 100

    joint1_position_controller:
        type: velocity_controllers/JointPositionController
        joint: panda_joint1
        pid: {p: 10000.0, i: 1.0, d: 1000.0, i_clamp: 10}

    joint2_position_controller:
        type: velocity_controllers/JointPositionController
        joint: panda_joint2
        pid: {p: 100.0, i: 0.1, d: 20.0, i_clamp: 1.0}

    joint3_position_controller:
        type: velocity_controllers/JointPositionController
        joint: panda_joint3
        pid: {p: 500.0, i: 0.01, d: 10.0, i_clamp: 0.1}

    joint4_position_controller:
        type: velocity_controllers/JointPositionController
        joint: panda_joint4
        pid: {p: 400.0, i: 0.0, d: 10.0}

    joint5_position_controller:
        type: velocity_controllers/JointPositionController
        joint: panda_joint5
        pid: {p: 6.5, i: 0.0, d: 0.01}

    joint6_position_controller:
        type: velocity_controllers/JointPositionController
        joint: panda_joint6
        pid: {p: 8.0, i: 0.0, d: 0.01}

    joint7_position_controller:
        type: velocity_controllers/JointPositionController
        joint: panda_joint7
        pid: {p: 12.0, i: 0.0, d: 0.1}

    joint1_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint1

    joint2_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint2

    joint3_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint3

    joint4_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint4

    joint5_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint5

    joint6_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint6

    joint7_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint7

    panda_hand_controller:
        type: velocity_controllers/JointTrajectoryController
        joints:
            - panda_finger_joint1
            - panda_finger_joint2

        gains:
            panda_finger_joint1: { p: 5, d: 3.0, i: 0, i_clamp: 1 }
            panda_finger_joint2: { p: 5, d: 1.0, i: 0, i_clamp: 1 }

        state_publish_rate: 25
