
    
    
    # Publish joint states
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    panda_arm_controller:
        type: velocity_controllers/JointTrajectoryController
        joints:
            - panda_joint1
            - panda_joint2
            - panda_joint3
            - panda_joint4
            - panda_joint5
            - panda_joint6
            - panda_joint7

        gains:
            panda_joint1: { p: 12000, d: 50, i: 0.0, i_clamp: 10000 }
            panda_joint2: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }
            panda_joint3: { p: 18000, d: 50, i: 0.01, i_clamp: 1 }
            panda_joint4: { p: 18000, d: 70, i: 0.01, i_clamp: 10000 }
            panda_joint5: { p: 12000, d: 70, i: 0.01, i_clamp: 1 }
            panda_joint6: { p: 7000, d: 50, i: 0.01, i_clamp: 1 }
            panda_joint7: { p: 2000, d: 20, i: 0.0, i_clamp: 1 }

        constraints:
            goal_time: 2.0

        state_publish_rate: 25
        state_publish_rate: 100

    # joint1_position_controller:
    #     type: velocity_controllers/JointPositionController
    #     joint: joint1
    #     pid: {p: 100.0, i: 0.01, d: 10.0}
    
    # joint2_position_controller:
    #     type: velocity_controllers/JointPositionController
    #     joint: panda_joint2
    #     pid: {p: 100.0, i: 0.01, d: 10.0}

    # joint3_position_controller:
    #     type: velocity_controllers/JointPositionController
    #     joint: panda_joint3
    #     pid: {p: 100.0, i: 0.01, d: 10.0}

    # joint4_position_controller:
    #     type: velocity_controllers/JointPositionController
    #     joint: panda_joint4
    #     pid: {p: 100.0, i: 0.01, d: 10.0}

    # joint5_position_controller:
    #     type: velocity_controllers/JointPositionController
    #     joint: panda_joint5
    #     pid: {p: 100.0, i: 0.01, d: 10.0}

    # joint6_position_controller:
    #     type: velocity_controllers/JointPositionController
    #     joint: panda_joint6
    #     pid: {p: 100.0, i: 0.01, d: 10.0}

    # joint7_position_controller:
    #     type: velocity_controllers/JointPositionController
    #     joint: panda_joint7
    #     pid: {p: 100.0, i: 0.01, d: 10.0}

    panda_arm_controller1:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint1
        publish_rate: 50

    
    panda_arm_controller2:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint2
        
    panda_arm_controller3:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint3

    panda_arm_controller4:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint4

    panda_arm_controller5:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint5

    panda_arm_controller6:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint6

    panda_arm_controller7:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint7


    panda_hand_controller:
        type: velocity_controllers/JointTrajectoryController
        joints:
            - panda_finger_joint1
            - panda_finger_joint2

        gains:
            panda_finger_joint1: { p: 5, d: 3.0, i: 0, i_clamp: 1 }
            panda_finger_joint2: { p: 5, d: 1.0, i: 0, i_clamp: 1 }

        state_publish_rate: 25

    