
    
    
    # Publish joint states
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    panda_arm_controller1:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint1
        publish_rate: 50

    
    panda_arm_controller2:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint2
        
    panda_arm_controller3:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint3

    panda_arm_controller4:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint4

    panda_arm_controller5:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint5

    panda_arm_controller6:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint6

    panda_arm_controller7:
        type: velocity_controllers/JointVelocityController
        joint: panda_joint7


    panda_hand_controller:
        type: velocity_controllers/JointTrajectoryController
        joints:
            - panda_finger_joint1
            - panda_finger_joint2

        gains:
            panda_finger_joint1: { p: 5, d: 3.0, i: 0, i_clamp: 1 }
            panda_finger_joint2: { p: 5, d: 1.0, i: 0, i_clamp: 1 }

        state_publish_rate: 25

    